sudo: false
language: node_js
node_js: 8
before_install:
- openssl aes-256-cbc -K $encrypted_f53d498de89d_key -iv $encrypted_f53d498de89d_iv
  -in id_rsa_deploy.enc -out id_rsa_deploy -d
- chmod 600 id_rsa_deploy
install:
- npm install '@angular/cli' -g
- npm install -g travis-ci-cloudfront-invalidation
- npm install
- npm list || true
- gem install compass
- cd node_modules/map-wald && npm install && (npm list || true) && cd -
script:
- npm config ls -l
- echo $TRAVIS_BRANCH
- node --version
- ng version
- cd node_modules/map-wald && npm run build && rm -rf node_modules && cd -
- SCRIPTS_FN=src/environments/environment.prod.ts
- sed "s/WENFO_GOOGLE_MAPS_API_KEY/$GOOGLE_MAPS_API_KEY/g" < $SCRIPTS_FN > tmp
- mv tmp $SCRIPTS_FN
- env BRANCH=$TRAVIS_BRANCH npm run build
- cat dist/index.html
deploy:
- skip_cleanup: true
  provider: script
  script: cd dist && scp -o StrictHostKeyChecking=no -i ../id_rsa_deploy -r . $FTP_USER@wenfo.org:/home/$FTP_USER/public_html/ternanu/staging
  on:
    branch: master
- skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_DEFAULT_REGION"
  bucket: "$AWS_S3_BUCKET"
  local_dir: dist
  on:
    branch: production
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY
  -c $CLOUDFRONT_DISTRIBUTION_ID -i "/*" -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
  -o "production"
notifications:
  email: false
  slack:
    rooms: wenfo:N1YfzQWaJ8wfjvrYarrh33PZ
    on_success: always
