sudo: false
language: node_js
node_js: 8
install:
  - npm install '@angular/cli' -g
  - npm install
  - gem install compass
  - cd node_modules/map-wald && npm install && cd -
script:
  - npm config ls -l
  - echo $TRAVIS_BRANCH
  - node --version
  - ng version
  - cd node_modules/map-wald && npm run build && rm -rf node_modules && cd -
  - SCRIPTS_FN=src/environments/environment.prod.ts
  - sed "s/WENFO_GOOGLE_MAPS_API_KEY/$GOOGLE_MAPS_API_KEY/g" < $SCRIPTS_FN > tmp
  - mv tmp $SCRIPTS_FN
  - env BRANCH=$TRAVIS_BRANCH npm run build
  - cat dist/index.html
deploy:
  # deploy to "wenfo.org/ternanu/staging" on branch master
  # - skip_cleanup: true
  #   provider: script
  #   script: bash -c "cd dist && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.wenfo.org/staging/{} \;"
  #   on:
  #     branch: master
  # deploy to "wenfo.org/ternanu" on branch production
  - skip_cleanup: true
    provider: script
    script: bash -c "cd dist && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.wenfo.org{} \;"
    on:
      branch: production
  - skip_cleanup: true
    provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: "$AWS_DEFAULT_REGION"
    bucket: "$AWS_S3_BUCKET"
    local_dir: dist
    on:
      branch: master

notifications:
  email: false
  slack:
    rooms: wenfo:N1YfzQWaJ8wfjvrYarrh33PZ
    on_success: always
